services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks: 
      - inception
    restart: on-failure

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure


networks:
  inception:
    name: inception


volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/rastie/data/web'

  mariadb:
    name: mariadb
    driver: local
    driver_opts:  
      type: 'none' 
      o: 'bind'
      device: '/home/rastie/data/database'