services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    volumes:
      - /home/rastie/data/database:/var/lib/mysql
    env_file:
      - .env
    networks: 
      - inception
    restart: on-failure

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    expose:
      - "9000"
    volumes:
      - /home/rastie/data/web:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /home/rastie/data/web:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure


networks:
  inception:
    name: inception